// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABvJGnr2WknDhbb2WrFuAkytHtvixpbNE',
    appId: '1:92053975450:web:920d7f33e0df02b8a40a23',
    messagingSenderId: '92053975450',
    projectId: 'architect-study-app',
    authDomain: 'architect-study-app.firebaseapp.com',
    storageBucket: 'architect-study-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltSGjV3ekqJj64r_-YCKCWALWOtHaKsY',
    appId: '1:92053975450:android:efd0b4e837858490a40a23',
    messagingSenderId: '92053975450',
    projectId: 'architect-study-app',
    storageBucket: 'architect-study-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Xs6QFCf_-3a02DXKt0JwHDq4WyHVnrg',
    appId: '1:92053975450:ios:c3456b3778224d32a40a23',
    messagingSenderId: '92053975450',
    projectId: 'architect-study-app',
    storageBucket: 'architect-study-app.firebasestorage.app',
    iosBundleId: 'com.archedu.architectulaEducationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Xs6QFCf_-3a02DXKt0JwHDq4WyHVnrg',
    appId: '1:92053975450:ios:c3456b3778224d32a40a23',
    messagingSenderId: '92053975450',
    projectId: 'architect-study-app',
    storageBucket: 'architect-study-app.firebasestorage.app',
    iosBundleId: 'com.archedu.architectulaEducationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC771DfsdPiV0jep6j5XIB6RnINkjyoVJM',
    appId: '1:92053975450:web:fb471487b8222b9ea40a23',
    messagingSenderId: '92053975450',
    projectId: 'architect-study-app',
    authDomain: 'architect-study-app.firebaseapp.com',
    storageBucket: 'architect-study-app.firebasestorage.app',
  );
}
